/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Alumnos;

import DTOs.AlumnoDTO;
import Facade.AlumnoFacade;
import DAOs.CarreraDao;
import Dominio.CarreraDominio;
import Enumeradores.EstadoAlumnos;
import NegocioException.NegocioException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author joel_
 */
public class AgregarAlumnos extends javax.swing.JDialog {

    private AlumnoFacade alumFcd = new AlumnoFacade();
    private CarreraDao carrDao = new CarreraDao();

    /**
     * Creates new form AgregarAlumnos
     */
    public AgregarAlumnos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        NombreTxt = new javax.swing.JTextField();
        ApellidoPaternoLabel = new javax.swing.JLabel();
        ApellidoPaternoTxt = new javax.swing.JTextField();
        ApellidoMaternoLabel = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        CarreraLabel = new javax.swing.JLabel();
        CarreraBox = new javax.swing.JComboBox<>();
        ContraseñaLabel = new javax.swing.JLabel();
        ContraseñaTxt = new javax.swing.JPasswordField();
        AgregarAlumnoButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TituloLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo.png"))); // NOI18N

        NombreLabel.setText("Nombre");

        NombreTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreTxtActionPerformed(evt);
            }
        });

        ApellidoPaternoLabel.setText("Apellido Paterno");

        ApellidoPaternoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidoPaternoTxtActionPerformed(evt);
            }
        });

        ApellidoMaternoLabel.setText("Apellido Materno");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        CarreraLabel.setText("Carrera");

        CarreraDao cDAO = new CarreraDao();
        DefaultComboBoxModel<CarreraDominio> carrerasModel = new DefaultComboBoxModel<CarreraDominio>();
        List<CarreraDominio> carreras = cDAO.obtenerCarreras();
        List<String> nombres = carreras.stream()
        .map(CarreraDominio::getNombre)
        .collect(Collectors.toList());

        DefaultComboBoxModel<String> modeloNombres = new DefaultComboBoxModel<>();
        for (String nombre : nombres) {
            modeloNombres.addElement(nombre);
        }
        CarreraBox.setModel(modeloNombres);

        ContraseñaLabel.setText("Contraseña");

        ContraseñaTxt.setText("jPasswordField1");

        AgregarAlumnoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AgregarAlumno.png"))); // NOI18N
        AgregarAlumnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarAlumnoButtonMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/CancelarButton.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NombreLabel)
                            .addComponent(NombreTxt)
                            .addComponent(ApellidoPaternoLabel)
                            .addComponent(ApellidoPaternoTxt)
                            .addComponent(ApellidoMaternoLabel)
                            .addComponent(jTextField1)
                            .addComponent(CarreraLabel)
                            .addComponent(CarreraBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContraseñaLabel)
                            .addComponent(ContraseñaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(AgregarAlumnoButton)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TituloLabel)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidoPaternoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidoPaternoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ApellidoMaternoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarreraLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CarreraBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContraseñaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContraseñaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarAlumnoButton)
                    .addComponent(jLabel2)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreTxtActionPerformed

    private void ApellidoPaternoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApellidoPaternoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoPaternoTxtActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void AgregarAlumnoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarAlumnoButtonMouseClicked
        alumFcd = new AlumnoFacade();
        AlumnoDTO alumno = new AlumnoDTO();
        alumno.setNombre(NombreTxt.getText());
        alumno.setApellidoPaterno(ApellidoPaternoTxt.getText());
        alumno.setApellidoMaterno(ApellidoPaternoTxt.getText());
        char[] passwordChars = ContraseñaTxt.getPassword(); // obtiene el arreglo de chars
        String contraseña = new String(passwordChars);      // convierte a String

        alumno.setContraseña(contraseña);
        alumno.setEstado(EstadoAlumnos.ESTUDIANDO);
        alumno.setCarrera(carrDao.buscarPorNombre((String) CarreraBox.getSelectedItem()));
        try {
            alumFcd.Registrar(alumno);
            Map<String, Object> parametros = new HashMap<>();

            parametros.put("nombre", alumno.getNombre());
            parametros.put("apellidoPaterno", alumno.getApellidoPaterno());
            parametros.put("apellidoMaterno", alumno.getApellidoMaterno());
            parametros.put("estado", alumno.getEstado().toString()); // asumiendo Enum

            JasperReport reporte = JasperCompileManager.compileReport(
                    getClass().getResourceAsStream("/reportes/reporte_alumno.jrxml"));

            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, new JREmptyDataSource());
            JasperViewer.viewReport(print, false);

        } catch (NegocioException ex) {
            Logger.getLogger(AgregarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(AgregarAlumnos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AgregarAlumnoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AgregarAlumnos dialog = new AgregarAlumnos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarAlumnoButton;
    private javax.swing.JLabel ApellidoMaternoLabel;
    private javax.swing.JLabel ApellidoPaternoLabel;
    private javax.swing.JTextField ApellidoPaternoTxt;
    private javax.swing.JComboBox<String> CarreraBox;
    private javax.swing.JLabel CarreraLabel;
    private javax.swing.JLabel ContraseñaLabel;
    private javax.swing.JPasswordField ContraseñaTxt;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JTextField NombreTxt;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
