/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AdministradorVentanas;


import Alumnos.AgregarAlumnos;
import Alumnos.DLGBloquearAlumno;
import Alumnos.DLGDesbloquearAlumno;
import Reportes.DLGGenerarReporteCarreras;
import javax.swing.JDialog;

/**
 *
 * @author joel_
 */
public class FRMAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FRMAdmin
     */
    public FRMAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlumnosButton = new javax.swing.JLabel();
        ReportesButton = new javax.swing.JLabel();
        LaboratorioButton = new javax.swing.JLabel();
        menuAlumnos = new PanelMenuAlumno();
        DesbloqueoButton = new javax.swing.JLabel();
        BloqueoButton = new javax.swing.JLabel();
        AgregarAlumnoButton = new javax.swing.JLabel();
        menuReportes = new PanelMenuReportes();
        ReporteCarreraButton = new javax.swing.JLabel();
        MenuLaboratorios = new PanelMenuLaboratorio();
        AñadirLaboratorioButton = new javax.swing.JLabel();
        GestionarLaboratorioButton = new javax.swing.JLabel();
        AgregarComputadoraButton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(179, 209, 214));
        setMaximumSize(new java.awt.Dimension(720, 480));
        setMinimumSize(new java.awt.Dimension(720, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlumnosButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonAlumnos.png"))); // NOI18N
        AlumnosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AlumnosButtonMouseClicked(evt);
            }
        });
        getContentPane().add(AlumnosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 22, -1, -1));

        ReportesButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonReportes.png"))); // NOI18N
        ReportesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportesButtonMouseClicked(evt);
            }
        });
        getContentPane().add(ReportesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 22, -1, -1));

        LaboratorioButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/BotonLaboratorios.png"))); // NOI18N
        LaboratorioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LaboratorioButtonMouseClicked(evt);
            }
        });
        getContentPane().add(LaboratorioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 22, -1, -1));

        menuAlumnos.setPreferredSize(new java.awt.Dimension(148, 114));

        DesbloqueoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DesbloqueoButtonMouseClicked(evt);
            }
        });

        BloqueoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BloqueoButtonMouseClicked(evt);
            }
        });

        AgregarAlumnoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarAlumnoButtonMouseClicked(evt);
            }
        });

        menuAlumnos.setVisible(false);

        javax.swing.GroupLayout menuAlumnosLayout = new javax.swing.GroupLayout(menuAlumnos);
        menuAlumnos.setLayout(menuAlumnosLayout);
        menuAlumnosLayout.setHorizontalGroup(
            menuAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuAlumnosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BloqueoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(DesbloqueoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AgregarAlumnoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        menuAlumnosLayout.setVerticalGroup(
            menuAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuAlumnosLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(AgregarAlumnoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BloqueoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DesbloqueoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        getContentPane().add(menuAlumnos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        menuReportes.setPreferredSize(new java.awt.Dimension(188, 40));

        ReporteCarreraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReporteCarreraButtonMouseClicked(evt);
            }
        });

        menuReportes.setVisible(false);

        javax.swing.GroupLayout menuReportesLayout = new javax.swing.GroupLayout(menuReportes);
        menuReportes.setLayout(menuReportesLayout);
        menuReportesLayout.setHorizontalGroup(
            menuReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuReportesLayout.createSequentialGroup()
                .addComponent(ReporteCarreraButton, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addContainerGap())
        );
        menuReportesLayout.setVerticalGroup(
            menuReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuReportesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ReporteCarreraButton, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );

        getContentPane().add(menuReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, -1, 40));

        MenuLaboratorios.setPreferredSize(new java.awt.Dimension(168, 103));

        AñadirLaboratorioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AñadirLaboratorioButtonMouseClicked(evt);
            }
        });

        GestionarLaboratorioButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GestionarLaboratorioButtonMouseClicked(evt);
            }
        });

        AgregarComputadoraButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarComputadoraButtonMouseClicked(evt);
            }
        });

        MenuLaboratorios.setVisible(false);

        javax.swing.GroupLayout MenuLaboratoriosLayout = new javax.swing.GroupLayout(MenuLaboratorios);
        MenuLaboratorios.setLayout(MenuLaboratoriosLayout);
        MenuLaboratoriosLayout.setHorizontalGroup(
            MenuLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLaboratoriosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MenuLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AñadirLaboratorioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GestionarLaboratorioButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addComponent(AgregarComputadoraButton, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                .addContainerGap())
        );
        MenuLaboratoriosLayout.setVerticalGroup(
            MenuLaboratoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLaboratoriosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(AñadirLaboratorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GestionarLaboratorioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AgregarComputadoraButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(MenuLaboratorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlumnosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlumnosButtonMouseClicked
        menuAlumnos.setVisible(!menuAlumnos.isVisible());
        System.out.println("click hecho");
    }//GEN-LAST:event_AlumnosButtonMouseClicked

    private void DesbloqueoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DesbloqueoButtonMouseClicked
        System.out.println("Desbloqueado");
        DLGDesbloquearAlumno dlgDesbloc = new DLGDesbloquearAlumno(this, true);
        dlgDesbloc.setLocationRelativeTo(null);
        dlgDesbloc.setVisible(true);
    }//GEN-LAST:event_DesbloqueoButtonMouseClicked

    private void BloqueoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BloqueoButtonMouseClicked
        DLGBloquearAlumno dlgBloc = new DLGBloquearAlumno(this, true);
        dlgBloc.setLocationRelativeTo(null);
        dlgBloc.setVisible(true);
    }//GEN-LAST:event_BloqueoButtonMouseClicked

    private void ReporteCarreraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReporteCarreraButtonMouseClicked
        System.out.println("Carrera");
        DLGGenerarReporteCarreras dlgCarrera = new DLGGenerarReporteCarreras(this, true);
        dlgCarrera.setLocationRelativeTo(null);
        dlgCarrera.setVisible(true);
   
    }//GEN-LAST:event_ReporteCarreraButtonMouseClicked

    private void AgregarAlumnoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarAlumnoButtonMouseClicked
        System.out.println("Alumno Agregado");
        AgregarAlumnos agregarfrm = new AgregarAlumnos(this, true);
        agregarfrm.setLocationRelativeTo(null);
        agregarfrm.setVisible(true);
    }//GEN-LAST:event_AgregarAlumnoButtonMouseClicked

    private void AñadirLaboratorioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AñadirLaboratorioButtonMouseClicked
        System.out.println("Laboratorio Añadido");
    }//GEN-LAST:event_AñadirLaboratorioButtonMouseClicked

    private void GestionarLaboratorioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GestionarLaboratorioButtonMouseClicked
        System.out.println("GESTION lABORATORIO");
    }//GEN-LAST:event_GestionarLaboratorioButtonMouseClicked

    private void AgregarComputadoraButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarComputadoraButtonMouseClicked
        System.out.println("Computadora Agregada");
    }//GEN-LAST:event_AgregarComputadoraButtonMouseClicked

    private void ReportesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesButtonMouseClicked
        menuReportes.setVisible(!menuReportes.isVisible());
    }//GEN-LAST:event_ReportesButtonMouseClicked

    private void LaboratorioButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LaboratorioButtonMouseClicked
        MenuLaboratorios.setVisible(!MenuLaboratorios.isVisible());
    }//GEN-LAST:event_LaboratorioButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgregarAlumnoButton;
    private javax.swing.JLabel AgregarComputadoraButton;
    private javax.swing.JLabel AlumnosButton;
    private javax.swing.JLabel AñadirLaboratorioButton;
    private javax.swing.JLabel BloqueoButton;
    private javax.swing.JLabel DesbloqueoButton;
    private javax.swing.JLabel GestionarLaboratorioButton;
    private javax.swing.JLabel LaboratorioButton;
    private javax.swing.JPanel MenuLaboratorios;
    private javax.swing.JLabel ReporteCarreraButton;
    private javax.swing.JLabel ReportesButton;
    private javax.swing.JPanel menuAlumnos;
    private javax.swing.JPanel menuReportes;
    // End of variables declaration//GEN-END:variables
}
